# Generated by Django 5.2.4 on 2025-07-25 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referralrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralrelationship',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to='referrals.profile'),
        ),
        migrations.AlterField(
            model_name='referralrelationship',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to='referrals.profile'),
        ),
    ]
